AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  pTableName:
    Type: String
  pBillingMode:
    Type: String
    Default: PAY_PER_REQUEST
    AllowedValues: [PAY_PER_REQUEST,PROVISIONED]
  pDeletionPolicy:
    Type: String
    Default: Retain
    AllowedValues: [Retain,Delete]
  pProvisionedThroughputRead:
    Type: Number
    Default: 5
  pProvisionedThroughputWrite:
    Type: Number
    Default: 5
  pAttribute0:
    Type: CommaDelimitedList
  pKey0:
    Type: CommaDelimitedList

  pAttribute1:
    Type: CommaDelimitedList
    Default: "none,none"
  pKey1:
    Type: CommaDelimitedList
    Default: "none,none"
  pAttribute2:
    Type: CommaDelimitedList
    Default: "none,none"
  pKey2:
    Type: CommaDelimitedList
    Default: "none,none"
  pAttribute3:
    Type: CommaDelimitedList
    Default: "none,none"
  pKey3:
    Type: CommaDelimitedList
    Default: "none,none"    
  pAttribute4:
    Type: CommaDelimitedList
    Default: "none,none"
  pKey4:
    Type: CommaDelimitedList
    Default: "none,none"
  pAttribute5:
    Type: CommaDelimitedList
    Default: "none,none"
  pKey5:
    Type: CommaDelimitedList
    Default: "none,none"
  pAttribute6:
    Type: CommaDelimitedList
    Default: "none,none"
  pKey6:
    Type: CommaDelimitedList
    Default: "none,none"    

Conditions:
  IsProvisioned: !Equals [!Ref pBillingMode, PROVISIONED]
  HasAttribute1: !Not [!Equals [!Select [0, !Ref pAttribute1], none]]
  HasAttribute2: !Not [!Equals [!Select [0, !Ref pAttribute2], none]]
  HasAttribute3: !Not [!Equals [!Select [0, !Ref pAttribute3], none]]
  HasAttribute4: !Not [!Equals [!Select [0, !Ref pAttribute4], none]]
  HasAttribute5: !Not [!Equals [!Select [0, !Ref pAttribute5], none]]
  HasAttribute6: !Not [!Equals [!Select [0, !Ref pAttribute6], none]]


Resources:
  rDynamoDbTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: !Ref pDeletionPolicy
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: !If [HasAttribute1, !Select [0, !Ref pAttribute1], !Ref AWS::NoValue]
          AttributeType: !If [HasAttribute1, !Select [1, !Ref pAttribute1], !Ref AWS::NoValue]
        - AttributeName: !If [HasAttribute2, !Select [0, !Ref pAttribute2], !Ref AWS::NoValue]
          AttributeType: !If [HasAttribute2, !Select [1, !Ref pAttribute2], !Ref AWS::NoValue]
        - AttributeName: !If [HasAttribute3, !Select [0, !Ref pAttribute3], !Ref AWS::NoValue]
          AttributeType: !If [HasAttribute3, !Select [1, !Ref pAttribute3], !Ref AWS::NoValue]
        - AttributeName: !If [HasAttribute4, !Select [0, !Ref pAttribute4], !Ref AWS::NoValue]
          AttributeType: !If [HasAttribute4, !Select [1, !Ref pAttribute5], !Ref AWS::NoValue]
        - AttributeName: !If [HasAttribute5, !Select [0, !Ref pAttribute5], !Ref AWS::NoValue]
          AttributeType: !If [HasAttribute5, !Select [1, !Ref pAttribute5], !Ref AWS::NoValue]
        - AttributeName: !If [HasAttribute6, !Select [0, !Ref pAttribute6], !Ref AWS::NoValue]
          AttributeType: !If [HasAttribute6, !Select [1, !Ref pAttribute6], !Ref AWS::NoValue]
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: !Ref pBillingMode
      ProvisionedThroughput: 
        ReadCapcityUnits: !If [IsProvisioned, !Ref pProvisionedThroughputRead, 0]
        WriteCapacityUnits: !If [IsProvisioned, !Ref pProvisionedThroughputWrite, 0]
      TableName: !Ref pTableName

Outputs:
  BucketName:
    Description: Table Name
    Value: !Ref rDynamoDbTable
  BucketArn:
    Description: Table ARN
    Value: !GetAtt rDynamoDbTable.Arn
