service: serverless-http-api-dynamodb
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  deploymentBucket:
    name: circleci.roar200-${env:DEPLOY_ENVIRONMENT}-deployment-bucket
  environment:
    DYNAMODB_TABLE: ${self:service}-${sls:stage}
  httpApi:
    cors: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  create:
    handler: src/create.create
    events:
      - httpApi:
          path: /todos
          method: post

  list:
    handler: src/list.list
    events:
      - httpApi:
          path: /todos
          method: get

  get:
    handler: src/get.get
    events:
      - httpApi:
          path: /todos/{id}
          method: get

  update:
    handler: src/update.update
    events:
      - httpApi:
          path: /todos/{id}
          method: put

  delete:
    handler: src/delete.delete
    events:
      - httpApi:
          path: /todos/{id}
          method: delete

resources:
  Resources:
    TodosDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
