version: 2.1

commands:
  change-node-version:
    parameters:
      version:
        type: string
    steps:
      - run:
          name: Install and Configure Node << parameters.version >>
          command: |
            wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
      - run:
          name: debug
          command: cat ~/.profile
      - run:
          name: Verify Install
          command: command -v nvm
      - run:
          command: |
            nvm install << parameters.version >>
            nvm use << parameters.version >>

  setup-yarn-cache:
    steps:
      - restore_cache: &yarnrestorecache
          name: Restoring Yarn Package Cache
          key: &yarncache yarn-packages-v1-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          no_output_timeout: &timeout 30m
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - save_cache:
          name: Caching Yarn Packages
          key: *yarncache
          paths:
            - ~/.cache/yarn
            - node_modules
  
  setup-pip-cache:
    steps:
      - restore_cache:
          name: Restoring pip cache
          key: &pipcachekey pipcache-v1-pyv3-8-9-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            pip install pipenv
            pipenv sync
      - save_cache:
          key: *pipcachekey
          paths:
            - ".venv"

jobs:
  main:
    docker: 
      - image: cimg/python:3.8.9-node
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - setup-pip-cache
      - run:
          name: Check version
          command: pipenv run runway --version
      - change-node-version:
          version: "12"
      - setup-yarn-cache
      - run:
          name: Check version
          command: yarn run sls --version

workflows:
  main:
    jobs:
      - main
