version: 2.1


jobs:
  main:
    docker: 
      - image: cimg/python:3.9.10
    steps:
      - run:
          name: "Hello, World!"
          command: "echo Hello, World!"
workflows:
  main:
    jobs:
      - main
