version: 2.1

commands:
  setup-yarn-cache:
    steps:
      - restore_cache: &yarnrestorecache
          name: Restoring Yarn Package Cache
          key: &yarncache yarn-packages-v1-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          no_output_timeout: &timeout 30m
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - save_cache:
          name: Caching Yarn Packages
          key: *yarncache
          paths:
            - ~/.cache/yarn
            - node_modules

jobs:
  main:
    docker: 
      - image: cimg/node:lts
    steps:
      - checkout
      - setup-yarn-cache
      - run:
          name: Check version
          command: yarn run sls --version
workflows:
  main:
    jobs:
      - main
