version: 2.1

commands:
  install-runway:
    steps:
      - run:
          name: Install Runway
          command: pipenv install
      - run:
          name: Validate Install
          command: pipenv run which runway
      - run:
          name: Check version
          command: pipenv run runway --version

jobs:
  main:
    docker: 
      - image: cimg/python:3.10.0
    steps:
      - install-runway
workflows:
  main:
    jobs:
      - main
