version: 2.1

commands:
  install-runway:
    steps:
      - run:
          name: Install Runway
          command: pipenv sync
      - run:
          name: Validate Install
          command: pipenv run which runway
      - run:
          name: Check version
          command: pipenv run runway --version

jobs:
  main:
    docker: 
      - image: cimg/python:3.8.9
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - install-runway
workflows:
  main:
    jobs:
      - main
